# Generated by Django 3.0.6 on 2020-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('category', models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salads', 'Salads'), ('Dinner Platters', 'Dinner Platters')], max_length=30, verbose_name='category')),
                ('size', models.CharField(choices=[('small', 'small'), ('large', 'large')], max_length=5, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meat', 'meat'), ('veggies', 'veggies')], max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
